dataset: Boussinesq_convection_flow_3d
# data directory
data_dir: './data/Boussinesq_convection_flow_3d'

# model and equation
model: 'spinn'
equation: 'Boussinesq_convection_flow_3d'

# input data settings
nt: 32
nxy: 128

# training settings
seed: 111
lr: 1e-3
epochs: 100000
offset_num: 8
offset_iter: 100
lbda_c: 5000.
lbda_rho: 100.
lbda_w: 100.
lbda_ic: 10000.
RBA: False
gamma: 0.999
eta_star: 0.01

# model settings
mlp: modified_mlp
n_layers: 3
features: 128
r: 128
out_dim: 3
pos_enc: 0

# time marching
marching_steps: 0
step_idx: 0
time_end: 1.2

# log settings
log_iter: 10000
plot_iter: 10000